name: New Jekyll site for crossroads.net
markdown: redcarpet
highlighter: true
port: 4002
relative_permalinks: false
baseurl: http://localhost:3000
feedurl: http://milacron.crossroads.net
exclude: ["vendor", "node_modules", "*.scss", "*.coffee"]
collections:
  content:
    output: true
  messages:  
    output: true  
  series:  
    output: true  
  media:  
    output: true 
  music:  
    output: true
  blog: 
    output: true 
  pages: 
    output: true
    
