name: New Jekyll site for crossroads.net
markdown: redcarpet
pygments: true
port: 4002
exclude: ["vendor", "node_modules"]  
prose:  
  rooturl: 'app/_posts'
  siteurl: 'http://milacron.crossroads.net/'
  relativeLinks: ''  
  ignore:  
    - _drafts  
    - clientside
    - fonts
    - .bowerrc
    - .gitignore
    - Gemfile
    - Gemfile.lock
    - Gruntfile.js
    - README.md
    - bower.json
    - config.rb
    - favicon.ico
    - index.html
    - package.json
    - _config.yml
  metadata:  
    _layouts:
      - name: "layout"
        field:
          element: "hidden"
          value: ""
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
    _posts:  
      - name: "published"
        field:
          element: "hidden"
          value: "true"  
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "comment"
        field:
          element: "checkbox"
          label: "Allow Comments"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""  
          placeholder: "Add title"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Add Category"
          placeholder: "Choose Categories"
          options:
            - name: "Milacron"
              value: "milacron"
            - name: "Other"
              value: "other"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Framework"
              value: "framework"
            - name: "Preprocessors"
              value: "preprocessors"
            - name: "CSS"
              value: "css"
            - name: "JavaScript"
              value: "javascript"  
      - name: "permalink"
        field:
          element: "text"
          label: "File Link"
          placeholder: "Add perma link"
          value: ""  
     
