name: New Jekyll site for crossroads.net
markdown: redcarpet
highlighter: true
port: 4002
relative_permalinks: false
exclude: ["vendor", "node_modules", "*.scss", "*.coffee"]
collections:
  blog: 
    output: true 
  content:
    output: true
  media:
    output: true  
  messages:
    output: true
  music:
    output: true 
  pages: 
    output: true
  series:
    output: true